'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { CHANNEL_NAME, currentReferent, DEFAULT_STATE, designId, LOG_KEY, REFERENTS, ResponseKind, SEQUENCES, STORAGE_KEY, StudyState } from '../study';

type TrialLog = Record<string, string | number | boolean>;
const emptyLog = (): TrialLog => ({ handCount:'', contactType:'', initialLocation:'', finalLocation:'', direction:'', pathShape:'', distance:'', surfaceArea:'', zDepth:'', maxDepthDuration:'', deformationRate:'', releasePattern:'', elicitationTime:'', gestureDuration:'', repetitions:1, hesitation:false, discreteContinuous:'', staticDynamic:'', singleMultiTouch:'', spatialNonSpatial:'', deformationPlanar:'', symbolicDirect:'', naturalness:0, confidence:0, explanation:'', expectedResponse:'', researcherNotes:'' });

const responseButtons: [string, ResponseKind][] = [['Traverse →','navigate'],['Nearby variation','local'],['Distant variation','broad'],['Broaden field','zoom-out'],['Save current state','anchor'],['Restore anchor','return-anchor'],['Create branch','branch'],['Lock component','lock'],['Unlock component','unlock'],['Undo','undo'],['Show comparison','compare'],['Show history','history'],['Reset','reset'],['Commit selection','select'],['Uncertain contact','uncertain']];

function Field({ label, value, onChange, type='text' }: { label:string; value:string|number|boolean; onChange:(v:string|number|boolean)=>void; type?:string }) { return <label className="form-field"><span>{label}</span>{type==='checkbox'?<input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>:<input type={type} value={String(value)} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)}/>}</label>; }
function SelectField({ label, value, options, onChange }: { label:string;value:string|number|boolean;options:string[];onChange:(v:string)=>void }) { return <label className="form-field"><span>{label}</span><select value={String(value)} onChange={e=>onChange(e.target.value)}><option value="">—</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>; }

export default function ResearcherPage(){
  const [state,setStateRaw]=useState<StudyState>(DEFAULT_STATE);
  const [log,setLog]=useState<TrialLog>(emptyLog());
  const [logs,setLogs]=useState<Record<string,TrialLog>>({});
  const [tab,setTab]=useState<'observe'|'session'|'interview'|'summary'>('observe');
  const [now,setNow]=useState(0);
  const channel=useRef<BroadcastChannel|null>(null);
  useEffect(()=>{
    const saved=localStorage.getItem(STORAGE_KEY);
    if(saved){
      const restored=JSON.parse(saved) as StudyState;
      const hydrated={...restored,sessionStartedAt:restored.sessionStartedAt||Date.now()};
      setStateRaw(hydrated);
      localStorage.setItem(STORAGE_KEY,JSON.stringify(hydrated));
    }else{
      const started={...DEFAULT_STATE,sessionStartedAt:Date.now()};
      setStateRaw(started);
      localStorage.setItem(STORAGE_KEY,JSON.stringify(started));
    }
    const savedLogs=localStorage.getItem(LOG_KEY);if(savedLogs)setLogs(JSON.parse(savedLogs));
    channel.current=new BroadcastChannel(CHANNEL_NAME);
    setNow(Date.now());
    const timer=window.setInterval(()=>setNow(Date.now()),1000);
    return()=>{window.clearInterval(timer);channel.current?.close();};
  },[]);
  const setState=(next:StudyState|((s:StudyState)=>StudyState))=>setStateRaw(prev=>{const value=typeof next==='function'?next(prev):next;localStorage.setItem(STORAGE_KEY,JSON.stringify(value));channel.current?.postMessage({type:'state',state:value});return value;});
  const ref=currentReferent(state); const elapsed=now&&state.sessionStartedAt?Math.max(0,now-state.sessionStartedAt):0; const elapsedText=`${String(Math.floor(elapsed/60000)).padStart(2,'0')}:${String(Math.floor(elapsed/1000)%60).padStart(2,'0')}`;
  const updateLog=(k:string,v:string|number|boolean)=>setLog(l=>({...l,[k]:v}));
  const saveLog=()=>{const enriched={...log,participantId:state.participantId,sequence:state.sequence,trialNumber:state.currentTrial+1,referentId:ref.id,referentLabel:ref.label,designId:designId(state.designIndex),savedAt:new Date().toISOString()};const next={...logs,[String(state.currentTrial)]:enriched};setLogs(next);localStorage.setItem(LOG_KEY,JSON.stringify(next));};
  const trigger=(response:ResponseKind)=>{setState(s=>{let anchors=s.anchors,locked=s.locked,branch=s.branch,designIndex=s.designIndex; if(response==='anchor'&&!anchors.includes(designIndex))anchors=[...anchors,designIndex];if(response==='lock'&&!locked.includes('Backrest'))locked=[...locked,'Backrest'];if(response==='unlock')locked=[];if(response==='branch')branch=`b${Number(s.branch.slice(1)||0)+1}`;if(['navigate','broad','local','zoom-out'].includes(response))designIndex=(designIndex+({navigate:2,broad:9,local:1,'zoom-out':6} as Record<string,number>)[response])%28;return{...s,response,screen:'responding',anchors,locked,branch,designIndex,overlayVisible:false};});window.setTimeout(()=>setState(s=>({...s,screen:'response-complete'})),850);};
  const show=(screen:StudyState['screen'],overlayVisible=true)=>setState(s=>({...s,screen,overlayVisible,response:screen==='trial'?'idle':s.response}));
  const nextTrial=()=>{saveLog();setState(s=>({...s,currentTrial:Math.min(14,s.currentTrial+1),screen:'trial',response:'idle',overlayVisible:true}));setLog(logs[String(Math.min(14,state.currentTrial+1))]||emptyLog());};
  const setRating=(key:'naturalness'|'confidence',v:number)=>updateLog(key,v);
  const exportData=(kind:'json'|'csv')=>{const rows=Object.values(logs);let text:string,type:string,name:string;if(kind==='json'){text=JSON.stringify({session:state,trials:rows},null,2);type='application/json';name=`${state.participantId}-latent-fabric.json`;}else{const keys=Object.keys(rows[0]||{});text=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');type='text/csv';name=`${state.participantId}-latent-fabric.csv`;}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);};
  const scores=useMemo(()=>Object.values(logs).map(l=>({n:Number(l.naturalness)||0,c:Number(l.confidence)||0})),[logs]);
  return <main className="researcher-app">
    <header className="researcher-header"><div><b>LATENT FABRIC</b><span>WIZARD-OF-OZ CONSOLE</span></div><div className="session-readout"><strong>{state.participantId} · MAIN ELICITATION</strong><span>TRIAL {String(state.currentTrial+1).padStart(2,'0')} / 15</span><span>{elapsedText}</span><span className={state.recording?'recording':''}>{state.recording?'● RECORDING':'Ⅱ PAUSED'}</span></div></header>
    <nav className="researcher-tabs">{(['observe','session','interview','summary'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t.toUpperCase()}</button>)}<a href="/" target="_blank">OPEN PARTICIPANT DISPLAY ↗</a></nav>
    {tab==='observe'&&<div className="researcher-grid">
      <aside className="trial-list"><div className="console-title">TRIAL ORDER · SEQUENCE {state.sequence}</div>{SEQUENCES[state.sequence].map((ri,i)=><button key={i} className={`${i===state.currentTrial?'active':''} ${logs[String(i)]?'done':''}`} onClick={()=>{saveLog();setState(s=>({...s,currentTrial:i,screen:'trial',response:'idle',overlayVisible:true}));setLog(logs[String(i)]||emptyLog());}}><span>{String(i+1).padStart(2,'0')}</span><b>{REFERENTS[ri].label}</b><small>{REFERENTS[ri].tier}</small></button>)}</aside>
      <section className="control-stack">
        <div className="referent-card"><div className="referent-meta"><span>CURRENT REFERENT · TIER {ref.tier}</span><strong>{ref.label}</strong></div><p>Participant sees: “{ref.prompt}”</p></div>
        <div className="workflow-card"><div className="console-title">TRIAL WORKFLOW</div><div className="workflow-grid"><button onClick={()=>show('trial')}>START TRIAL</button><button onClick={()=>show('captured')}>MARK FIRST CAPTURED</button><button onClick={()=>show('captured',false)}>MARK REPEAT CAPTURED</button><button className="primary-trigger" onClick={()=>trigger((ref.id==='explore-broadly'?'broad':ref.id==='refine-locally'?'local':ref.id==='anchor'?'anchor':ref.id==='return-anchor'?'return-anchor':ref.id==='branch'?'branch':ref.id==='lock'?'lock':ref.id==='select'?'select':ref.id) as ResponseKind)}>TRIGGER RESPONSE</button><button onClick={()=>show('question-why')}>WHY QUESTION</button><button onClick={()=>show('question-expect')}>EXPECTATION QUESTION</button><button onClick={()=>show('rating-naturalness')}>NATURALNESS</button><button onClick={()=>show('rating-confidence')}>CONFIDENCE</button></div></div>
        <div className="response-card"><div className="console-title">MOCK RESPONSE PALETTE</div><div className="response-grid">{responseButtons.map(([label,r])=><button onClick={()=>trigger(r)} key={r}>{label}</button>)}</div></div>
        <div className="transport"><button onClick={()=>setState(s=>({...s,currentTrial:Math.max(0,s.currentTrial-1)}))}>← PREVIOUS</button><button onClick={()=>setState(s=>({...s,recording:!s.recording}))}>{state.recording?'PAUSE SESSION':'RESUME SESSION'}</button><button className="next" onClick={nextTrial}>SAVE + NEXT TRIAL →</button></div>
      </section>
      <section className="observation-panel"><div className="console-title">GESTURE OBSERVATION · MANUAL LOG</div>
        <fieldset><legend>GEOMETRY</legend><SelectField label="Hands" value={log.handCount} options={['One hand','Two hands']} onChange={v=>updateLog('handCount',v)}/><SelectField label="Contact" value={log.contactType} options={['Finger','Multiple fingers','Palm','Whole hand']} onChange={v=>updateLog('contactType',v)}/><div className="two"><Field label="Initial region" value={log.initialLocation} onChange={v=>updateLog('initialLocation',v)}/><Field label="Final region" value={log.finalLocation} onChange={v=>updateLog('finalLocation',v)}/></div><div className="two"><SelectField label="Direction" value={log.direction} options={['Left','Right','Forward','Back','Inward','Outward','None']} onChange={v=>updateLog('direction',v)}/><SelectField label="Path" value={log.pathShape} options={['Linear','Curved','Circular','Irregular','Stationary']} onChange={v=>updateLog('pathShape',v)}/></div></fieldset>
        <fieldset><legend>DEFORMATION + TIME</legend><div className="three"><Field label="Z depth mm" type="number" value={log.zDepth} onChange={v=>updateLog('zDepth',v)}/><Field label="Max hold s" type="number" value={log.maxDepthDuration} onChange={v=>updateLog('maxDepthDuration',v)}/><SelectField label="Rate" value={log.deformationRate} options={['Slow','Moderate','Fast']} onChange={v=>updateLog('deformationRate',v)}/></div><div className="three"><Field label="Elicitation s" type="number" value={log.elicitationTime} onChange={v=>updateLog('elicitationTime',v)}/><Field label="Duration s" type="number" value={log.gestureDuration} onChange={v=>updateLog('gestureDuration',v)}/><Field label="Repetitions" type="number" value={log.repetitions} onChange={v=>updateLog('repetitions',v)}/></div><Field label="Hesitation observed" type="checkbox" value={log.hesitation} onChange={v=>updateLog('hesitation',v)}/></fieldset>
        <fieldset><legend>BEHAVIOURAL STRUCTURE</legend><div className="two"><SelectField label="Temporal" value={log.discreteContinuous} options={['Discrete','Continuous']} onChange={v=>updateLog('discreteContinuous',v)}/><SelectField label="Motion" value={log.staticDynamic} options={['Static','Dynamic']} onChange={v=>updateLog('staticDynamic',v)}/><SelectField label="Touch" value={log.singleMultiTouch} options={['Single-touch','Multitouch']} onChange={v=>updateLog('singleMultiTouch',v)}/><SelectField label="Spatial" value={log.spatialNonSpatial} options={['Spatial','Non-spatial']} onChange={v=>updateLog('spatialNonSpatial',v)}/><SelectField label="Modality" value={log.deformationPlanar} options={['Deformation-based','Planar','Mixed']} onChange={v=>updateLog('deformationPlanar',v)}/><SelectField label="Meaning" value={log.symbolicDirect} options={['Symbolic','Direct manipulation','Mixed']} onChange={v=>updateLog('symbolicDirect',v)}/></div></fieldset>
        <fieldset><legend>SUBJECTIVE</legend><div className="score-row"><span>NATURALNESS</span>{[1,2,3,4,5].map(n=><button className={Number(log.naturalness)===n?'selected':''} onClick={()=>setRating('naturalness',n)} key={n}>{n}</button>)}</div><div className="score-row"><span>CONFIDENCE</span>{[1,2,3,4,5].map(n=><button className={Number(log.confidence)===n?'selected':''} onClick={()=>setRating('confidence',n)} key={n}>{n}</button>)}</div><label className="text-field"><span>Why this action?</span><textarea value={String(log.explanation)} onChange={e=>updateLog('explanation',e.target.value)}/></label><label className="text-field"><span>Expected response</span><textarea value={String(log.expectedResponse)} onChange={e=>updateLog('expectedResponse',e.target.value)}/></label><label className="text-field notes"><span>Researcher notes</span><textarea value={String(log.researcherNotes)} onChange={e=>updateLog('researcherNotes',e.target.value)}/></label></fieldset>
      </section>
    </div>}
    {tab==='session'&&<Setup state={state} setState={setState} show={show}/>} 
    {tab==='interview'&&<Interview show={show}/>} 
    {tab==='summary'&&<section className="summary-panel"><div className="console-title">SESSION SUMMARY</div><div className="summary-cards"><div><span>TRIALS COMPLETED</span><b>{Object.keys(logs).length} / 15</b></div><div><span>AVG NATURALNESS</span><b>{scores.length?(scores.reduce((a,s)=>a+s.n,0)/scores.length).toFixed(1):'—'}</b></div><div><span>AVG CONFIDENCE</span><b>{scores.length?(scores.reduce((a,s)=>a+s.c,0)/scores.length).toFixed(1):'—'}</b></div><div><span>DEFORMATION USED</span><b>{Object.values(logs).filter(l=>Number(l.zDepth)>0).length}</b></div></div><div className="export-row"><button onClick={()=>exportData('json')}>EXPORT SESSION JSON</button><button onClick={()=>exportData('csv')}>EXPORT CSV</button><button onClick={()=>show('complete')}>SHOW SESSION COMPLETE</button></div></section>}
  </main>;
}

function Setup({state,setState,show}:{state:StudyState;setState:(f:(s:StudyState)=>StudyState)=>void;show:(s:StudyState['screen'])=>void}){return <section className="setup-panel"><div className="console-title">SESSION SETUP + PARTICIPANT DISPLAY</div><div className="setup-grid"><Field label="Participant ID" value={state.participantId} onChange={v=>setState(s=>({...s,participantId:String(v)}))}/><SelectField label="Counterbalanced sequence" value={state.sequence} options={['A','B','C','D']} onChange={v=>setState(s=>({...s,sequence:v as keyof typeof SEQUENCES,currentTrial:0}))}/><Field label="Researcher initials" value={state.researcherInitials} onChange={v=>setState(s=>({...s,researcherInitials:String(v)}))}/><Field label="Neutral elicitation mode" type="checkbox" value={state.studyNeutralMode} onChange={v=>setState(s=>({...s,studyNeutralMode:Boolean(v)}))}/></div><div className="phase-controls"><button onClick={()=>show('welcome')}>WELCOME</button><button onClick={()=>show('familiarization')}>FAMILIARIZATION</button><button onClick={()=>show('practice')}>PRACTICE</button><button onClick={()=>show('trial')}>MAIN ELICITATION</button><button onClick={()=>show('interview')}>POST-STUDY</button><button onClick={()=>show('complete')}>COMPLETE</button></div></section>}

const questions=['What did moving across the fabric mean to you?','What did pushing or deforming it mean to you?','Which actions felt most naturally physical?','Which actions would you rather perform using a visible button?','Which two actions felt most similar or potentially confusing?','Did you perceive the surface as a map, material, controller, landscape, or something else?','Did using one hand versus two hands carry different meanings?','Were there interactions you expected that we did not ask about?'];
function Interview({show}:{show:(s:StudyState['screen'])=>void}){return <section className="interview-panel"><div className="console-title">RESEARCHER-GUIDED POST-STUDY INTERVIEW</div><button className="show-interview" onClick={()=>show('interview')}>SHOW NEUTRAL INTERVIEW SCREEN TO PARTICIPANT</button>{questions.map((q,i)=><label className="interview-question" key={q}><b>{String(i+1).padStart(2,'0')}</b><span>{q}</span><textarea placeholder="Structured notes…"/></label>)}</section>}
